apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Production API
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mikkel@reload.dk
    privateKeySecretRef:
      name: tls-production
    solvers:
    - http01:
       ingress:
         class: nginx