---
version: '3'

tasks:
  install:
    desc: Setup storage class

    env:
      STORAGE_ACCOUNT_NAME:
        sh: terraform output -json | jq --raw-output ".storage_account_name.value"
      STORAGE_ACCOUNT_KEY:
        # TODO - would be nice to get some of these values from some config.
        sh: az keyvault secret show --subscription "3b95f745-ffb4-4ff8-b3f9-45308d6fc4b8" --name storage-primary-access-key --vault-name $(terraform output -json | jq --raw-output ".keyvault_name.value") --query value -o tsv
      STORAGE_SHARE_NAME:
        sh: terraform output -json | jq --raw-output ".storage_share_name.value"
      RESOURCE_GROUP: lag01

    cmds:
      - kubectl delete --ignore-not-found=true storageclass bulk
      - envsubst < manifests/storageclass.yaml | kubectl apply -f -
      - |
        kubectl create secret generic bulk \
          --from-literal=sharename=STORAGE_ACCOUNT_NAME \
          --from-literal=azurestorageaccountname=$STORAGE_ACCOUNT_NAME \
          --from-literal=azurestorageaccountkey=$STORAGE_ACCOUNT_KEY  \
          -o yaml \
          --dry-run=client \
          | kubectl apply -n kube-system -f -

  test-deploy:
    desc: "Do deployment of a storage test app, NAME is required"
    env:
      NAME: "{{.NAME}}"
    cmds:
      - envsubst < manifests/test-deployment.yaml | kubectl apply -f -
    preconditions:
      - sh: "[ ! -z {{.NAME}} ]"
        msg: "Env variable NAME is not set or empty."
