version: '3'

tasks:
  create:
    cmds:
      - kubectl create namespace ingress-basic
      - ./scripts/helmInstallnginxIngress.sh
      - ./scripts/helmInstallCertManager.sh
    deps:
    - is-installed-helm
    - is-installed-kubectl
  is-installed-helm:
    preconditions:
      - sh: "helm"
        msg: "helm is not installed. Cannot continue..."
  is-installed-kubectl:
    preconditions:
      - sh: "kubectl"
        msg: "kubectl is not installed. Cannot continue..."