version: '3'

tasks:
  create:
    cmds:
      - echo 'Hello Mikkel'
      # - kubectl create namespace ingress-basic
      # - ./scripts/helmInstallNginxIngress.sh
    deps:
    - is-installed-helm
    - is-installed-kubectl
  is-installed-helm:
    preconditions:
      - sh: "helm"
        msg: "helm is not installed. Cannot continue..."
  is-installed-kubectl:
    preconditions:
      - sh: "kubectl"
        msg: "kubectl is not installed. Cannot continue..."