version: '3'

includes:
  ingress: ./Ingress.task.yml
  cert-manager: ./CertManager.task.yml
  demo-apps: ./DemoApplications.task.yml

tasks:
  setup-ingress:
    cmds:
      - task: mount-ak
      # Setup Ingress.
      - task ingress:setup
      # Setup cert-manager.
      - task cert-manager:setup
      # Prove that Ingress and the cert manager work.
      - task demo-apps:install
  mount-ak:
    cmds:
      # Authenticate at Azure in order to get access to cluster.
      - az aks get-credentials --resource-group poc02-rg --name poc02-cluster