version: '3'

includes:
  common: ./Common.yml
  ingress: ./Ingress.yml
  demo-apps: ./DemoApplications.yml

tasks:
  setup-ingress:
    cmds:
      - task ingress:create
      - task demo-apps:install
