version: '3'

vars:
  workspace: '{{.WORKSPACE | default "poc02"}}'

includes:
  ingress: ./task_modules/Ingress/Taskfile.yml
  logging: ./task_modules/Loki/Taskfile.yml
  cert-manager: ./task_modules/CertManager/Taskfile.yml
  demo-apps: ./task_modules/DemoApplications/Taskfile.yml

tasks:

  # Build Azure kluster infrastructure.
  build-cluster:
    cmds:
      - terraform apply

  # Tear down aks cluster
  destroy-cluster:
    cmds:
      - terraform destroy

  # Installs ingress and cert manager.
  setup-ingress:
    deps: [mount-ak]
    cmds:
      # Setup Ingress.
      - task: ingress:setup
      # Setup cert-manager.
      - task: cert-manager:setup
 
  # Installs demo applications.
  setup-demo-apps:
    deps: [mount-ak]
    cmds:
      - task: demo-apps:install
 
 # Adds Loki logging.
  setup-logging:
    deps: [mount-ak]
    cmds:
      - task: logging:setup
 
 # Authenticates to aks cluster.
  mount-ak:
    cmds:
      - az aks get-credentials --resource-group {{.workspace}}-rg --name {{.workspace}}-cluster
 
  # Main task for running the whole show.
  setup:
    deps:
      - mount-ak
      - build-cluster
      - setup-ingress
      - setup-logging
    cmds:
      - task: setup-demo-apps