version: '3'

tasks:
  install:
    dir: "$TASK_MODULES_DIR/Loki"
    deps: [kube:create:ns, helm:repo:add:grafana]
    cmds:
      - helm upgrade --install loki -n loki -f conf/loki-values.yml grafana/loki
      - helm upgrade --install -n loki promtail grafana/promtail --set "loki.serviceName=loki" --set "config.lokiAddress=http://loki:3100/loki/api/v1/push"
      - helm upgrade --install grafana -n loki -f conf/grafana-values.yml grafana/grafana

  kube:create:ns:
    cmds:
      - kubectl create namespace loki --dry-run=client -o yaml | kubectl apply -f -

  helm:repo:add:grafana:
    cmds:
      - helm repo add grafana https://grafana.github.io/helm-charts && helm repo update

  grafana:get:password:
    cmds:
      - kubectl get secret -n loki grafana -o jsonpath="{.data.admin-password}" | base64 -d ; echo

  setup:
    cmds:
      - task: install
