version: '3'

env:
  MODULE_DIR:
    sh: echo $TASK_MODULES_DIR/Loki

tasks:
  install:
    deps: [add-ns, add-helm-repo]
    cmds:
      - helm upgrade --install loki -n loki -f $MODULE_DIR/conf/loki-values.yml grafana/loki
      - helm upgrade --install -n loki promtail grafana/promtail --set "loki.serviceName=loki" --set "config.lokiAddress=http://loki:3100/loki/api/v1/push"
      - helm upgrade --install grafana -n loki -f $MODULE_DIR/conf/grafana-values.yml grafana/grafana
  add-ns:
    cmds:
      - kubectl create namespace loki --dry-run=client -o yaml | kubectl apply -f -
  add-helm-repo:
    cmds:
      - helm repo add grafana https://grafana.github.io/helm-charts && helm repo update
  get-admin-password:
    cmds:
      - kubectl get secret -n loki grafana -o jsonpath="{.data.admin-password}" | base64 -d ; echo
  setup:
    cmds:
      - task: install
