version: '3'

tasks:
  kube:create:ns:
    desc: Creates ingress namespace if it does not exist.
    cmds:
      - kubectl create namespace ingress-basic --dry-run=client -o yaml | kubectl apply -f -
 
  install:
    desc: Installs Ingress.
    dir: "$TASK_MODULES_DIR/Ingress"
    deps: [kube:create:ns]
    cmds:
      - ./scripts/helmInstallnginxIngress.sh
      
  setup:
    desc: Setting up everything releated to Ingress.
    cmds:
      - task: install