version: '3'

tasks:
  install:
    desc: Installs demo application deployments and ingress resource.
    dir: "$TASK_MODULES_DIR/DemoApplications"
    cmds:
      - kubectl apply -f ./manifests/aks-helloworld-one.yaml -n ingress-basic
      - kubectl apply -f ./manifests/aks-helloworld-two.yaml -n ingress-basic
      - kubectl apply -f ./manifests/hello-world-ingress.yaml

