version: '3'

tasks:
  install:
    env:
      MARIADB_HOSTNAME:
        sh: terraform output -json | jq --raw-output ".mariadb_hostname.value"
      MARIADB_SERVERNAME:
        sh: terraform output -json | jq --raw-output ".mariadb_servername.value"
      MARIADB_USER:
        sh: terraform output -json | jq --raw-output ".mariadb_user.value"
      MARIADB_PASSWORD:
        sh: terraform output -json | jq --raw-output ".mariadb_password.value"
    desc: Installs Ingress.
    cmds:
      - curl https://raw.githubusercontent.com/amazeeio/lagoon/42bf55050d1bd1ddfd5b92cc6e3dafa3f31b0420/openshift-setup/dbaas-operator.yaml | kubectl apply -f -
      - envsubst < manifests/mariadbprovider.yaml | kubectl apply -f -

  test:
    desc: "Create test database"
    env:
      NAME: "{{.NAME}}"
    cmds:
      - envsubst < manifests/mariadbconsumer.yaml | kubectl apply -f -
    preconditions:
      - sh: "[ ! -z {{.NAME}} ]"
        msg: "Env variable NAME is not set or empty."
