---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bulk
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  skuName: Standard_LRS
  storageAccount: $STORAGE_ACCOUNT_NAME
  resourcegroup: $RESOURCE_GROUP

