version: '3'

vars:
  GRAFANA_PORT: 3000

tasks:
  install:
    desc: Installs Loki and dependencies.
    env:
      AZURE_STORAGE_CONTAINER_NAME:
        sh: terraform output -json | jq --raw-output ".azure_blob_storage_container_name.value"
      AZURE_STORAGE_ACCOUNT_NAME:
        sh: terraform output -json | jq --raw-output ".storage_account_name.value"
      AZURE_STORAGE_ACCOUNT_KEY:
        sh: terraform output -json | jq --raw-output ".azure_blob_storage_account_key.value"
    deps: [kube:create:ns, helm:repo:add:grafana]
    cmds:
      - ./scripts/helmInstallLoki.sh

  kube:create:ns:
    desc: Creates Loki namespace.
    cmds:
      - kubectl create namespace loki --dry-run=client -o yaml | kubectl apply -f -

  helm:repo:add:grafana:
    desc: Adds Grafana repo to Helm. Used by Loki and its dependencies.
    cmds:
      - helm repo add grafana https://grafana.github.io/helm-charts && helm repo update

  grafana:password:get:
    desc: Fetches the admin password for the Grafana web interface.
    cmds:
      - kubectl get secret -n loki grafana -o jsonpath="{.data.admin-password}" | base64 -d ; echo
  
  grafana:password:set:
    desc: Sets the admin password for the Grafana web interface.
    cmds:
      - kubectl exec -n loki --tty $(kubectl get pods -n loki -l "app.kubernetes.io/name=grafana,app.kubernetes.io/instance=grafana" -o jsonpath="{.items[0].metadata.name}") -- grafana-cli admin reset-admin-password {{.CLI_ARGS}}

  grafana:port:forward:
    desc: Forwards Grafana web interface port to localhost
    cmds:
      - kubectl -n loki port-forward $(kubectl get pods -n loki -l "app.kubernetes.io/name=grafana,app.kubernetes.io/instance=grafana" -o jsonpath="{.items[0].metadata.name}") {{.GRAFANA_PORT}}