on:
  push:
    paths:
      - "infrastructure/**.tf"
      - "infrastructure/**.tfvars"
      - ".github/workflows/terraform-lint.yaml"
name: Terraform Lint
jobs:
  terraform_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -check infrastructure/terraform
        continue-on-error: false
